### GET all users
GET http://localhost:3300/users

### GET user by ID
GET localhost:3300/users/2

### POST new user
POST localhost:3300/users
Content-Type: application/json

{
  "name": "POST teszt",
  "email": "teszt@teszt.com",
  "password": "pw123"
}


### DELETE user by ID
DELETE localhost:3300/users/1
Content-Type: application/json

### PATCH user password
PATCH localhost:3300/users/2/password
Content-Type: application/json

{
  "oldPassword": "pw123",
  "newPassword": "pw1234"
}



### GET all wallets
GET http://localhost:3300/wallets

### GET wallet by ID
GET http://localhost:3300/wallets/1

### GET all wallets by user ID
GET http://localhost:3300/wallets/user/2

### POST new wallet
POST http://localhost:3300/wallets
Content-Type: application/json

{
  "userID": 2,
  "name": "Side Wallet",
  "balance": 23
}

### PATCH wallet name by ID
PATCH http://localhost:3300/wallets/name/1
Content-Type: application/json

{
  "name": "Updated Wallet Name"
}

### PATCH wallet balance by ID
PATCH http://localhost:3300/wallets/balance/1
Content-Type: application/json

{
  "balance": 3000.00
}

### DELETE wallet by ID
DELETE http://localhost:3300/wallets/1



### GET all categories
GET http://localhost:3300/categories

### GET category by ID
GET http://localhost:3300/categories/1

### POST new category
POST http://localhost:3300/categories
Content-Type: application/json

{
  "name": "Szorakozas"
}

### PATCH category name by ID
PATCH http://localhost:3300/categories/name/1
Content-Type: application/json

{
  "name": "Bevasarlas"
}

### DELETE category by ID
DELETE http://localhost:3300/categories/1



### GET all transactions
GET http://localhost:3300/transactions

### GET transaction by ID
GET http://localhost:3300/transactions/3

### GET all transactions by wallet ID
GET http://localhost:3300/transactions/wallet/2

### GET all transactions by wallet ID and category ID
GET http://localhost:3300/transactions/wallet/2/category/2

### GET all transactions by wallet ID and type
GET http://localhost:3300/transactions/wallet/2/type/kiadas

### POST new transaction
POST http://localhost:3300/transactions
Content-Type: application/json

{
  "walletID": 2,
  "amount": 1250,
  "categoryID": 2,
  "type": "kiadas"
}

### PATCH transaction data by ID
PATCH http://localhost:3300/transactions/3
Content-Type: application/json

{
  "walletID": 2,
  "amount": 1500,
  "categoryID": 2,
  "type": "bevetel"
}

### DELETE transaction by ID
DELETE http://localhost:3300/transactions/1
