### GET all transactions
GET http://localhost:3300/transactions

### GET transaction by ID
GET http://localhost:3300/transactions/3

### GET all transactions by wallet ID
GET http://localhost:3300/transactions/wallet/2

### GET all transactions by wallet ID and category ID
GET http://localhost:3300/transactions/wallet/2/category/2

### GET all transactions by wallet ID and type
GET http://localhost:3300/transactions/wallet/2/type/kiadas

### POST new transaction
POST http://localhost:3300/transactions
Content-Type: application/json

{
  "walletID": 2,
  "amount": 1250,
  "categoryID": 2,
  "type": "kiadas"
}

### PATCH transaction data by ID
PATCH http://localhost:3300/transactions/3
Content-Type: application/json

{
  "walletID": 2,
  "amount": 1500,
  "categoryID": 2,
  "type": "bevetel"
}

### DELETE transaction by ID
DELETE http://localhost:3300/transactions/1
